### ISSUE TITLE
Macro runtime error

### ISSUE THREAD

**Issue by moaeddy** [trustedsec/unicorn#120] opened 2019-04-11 07:46 UTC
there is runtime error in Macro code image attached
![macro-error](https://user-images.githubusercontent.com/7292467/55939684-3d970a00-5bf3-11e9-902c-ab3dfbdc43f9.jpg)

**Comment by trustedsec** [comment] 2019-04-16 12:05
Hmm, I'm unable to reproduce this one. I'm using Windows 10 and on the latest version of Office.. Are you using an older version of Unicorn? My first line looks like this:

KQMrdppz = " /w 1 /C ""sv AZu -;sv Pd ec;sv O"

**Comment by trustedsec** [comment] 2019-04-24 17:43
This is fixed in the latest release

**Closed by trustedsec** 2019-04-24 17:43 UTC
